
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ASSIGN DELETE FDISK FIT ID MKDISK NAME NUMBER PATH PATHWITHOUTQUOTES PATHWITHQUOTES RMDISK SEPARATOR SIZE TYPE UNITinit : commandsIcommandsI : commandsI command\n                | commandcommand : mkdisk_block\n               | rmdisk_block\n               | fdisk_blockmkdisk_block : MKDISK mkdisk_paramsrmdisk_block : RMDISK SEPARATOR PATH ASSIGN PATHWITHQUOTES\n                    | RMDISK SEPARATOR PATH ASSIGN PATHWITHOUTQUOTESmkdisk_params : mkdisk_params mkdisk_param\n                     | mkdisk_parammkdisk_param : SEPARATOR SIZE ASSIGN NUMBER\n                    | SEPARATOR PATH ASSIGN PATHWITHQUOTES\n                    | SEPARATOR PATH ASSIGN PATHWITHOUTQUOTES\n                    | SEPARATOR UNIT ASSIGN ID\n                    | SEPARATOR FIT ASSIGN IDfdisk_block : FDISK fdisk_paramsfdisk_params : fdisk_params fdisk_param\n                    | fdisk_paramfdisk_param : SEPARATOR SIZE ASSIGN NUMBER\n                   | SEPARATOR PATH ASSIGN PATHWITHQUOTES\n                   | SEPARATOR PATH ASSIGN PATHWITHOUTQUOTES\n                   | SEPARATOR NAME ASSIGN ID\n                   | SEPARATOR NAME ASSIGN PATHWITHOUTQUOTES\n                   | SEPARATOR UNIT ASSIGN ID\n                   | SEPARATOR TYPE ASSIGN ID\n                   | SEPARATOR FIT ASSIGN ID\n                   | SEPARATOR DELETE ASSIGN ID\n                   | SEPARATOR ADD ASSIGN ID'
    
_lr_action_items = {'MKDISK':([0,2,3,4,5,6,10,11,12,15,16,18,24,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,],[7,7,-3,-4,-5,-6,-2,-7,-11,-17,-19,-10,-18,-12,-13,-14,-15,-16,-8,-9,-20,-21,-22,-23,-24,-25,-26,-27,-28,-29,]),'RMDISK':([0,2,3,4,5,6,10,11,12,15,16,18,24,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,],[8,8,-3,-4,-5,-6,-2,-7,-11,-17,-19,-10,-18,-12,-13,-14,-15,-16,-8,-9,-20,-21,-22,-23,-24,-25,-26,-27,-28,-29,]),'FDISK':([0,2,3,4,5,6,10,11,12,15,16,18,24,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,],[9,9,-3,-4,-5,-6,-2,-7,-11,-17,-19,-10,-18,-12,-13,-14,-15,-16,-8,-9,-20,-21,-22,-23,-24,-25,-26,-27,-28,-29,]),'$end':([1,2,3,4,5,6,10,11,12,15,16,18,24,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,],[0,-1,-3,-4,-5,-6,-2,-7,-11,-17,-19,-10,-18,-12,-13,-14,-15,-16,-8,-9,-20,-21,-22,-23,-24,-25,-26,-27,-28,-29,]),'SEPARATOR':([7,8,9,11,12,15,16,18,24,46,47,48,49,50,53,54,55,56,57,58,59,60,61,62,],[13,14,17,13,-11,17,-19,-10,-18,-12,-13,-14,-15,-16,-20,-21,-22,-23,-24,-25,-26,-27,-28,-29,]),'SIZE':([13,17,],[19,25,]),'PATH':([13,14,17,],[20,23,26,]),'UNIT':([13,17,],[21,28,]),'FIT':([13,17,],[22,30,]),'NAME':([17,],[27,]),'TYPE':([17,],[29,]),'DELETE':([17,],[31,]),'ADD':([17,],[32,]),'ASSIGN':([19,20,21,22,23,25,26,27,28,29,30,31,32,],[33,34,35,36,37,38,39,40,41,42,43,44,45,]),'NUMBER':([33,38,],[46,53,]),'PATHWITHQUOTES':([34,37,39,],[47,51,54,]),'PATHWITHOUTQUOTES':([34,37,39,40,],[48,52,55,57,]),'ID':([35,36,40,41,42,43,44,45,],[49,50,56,58,59,60,61,62,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'commandsI':([0,],[2,]),'command':([0,2,],[3,10,]),'mkdisk_block':([0,2,],[4,4,]),'rmdisk_block':([0,2,],[5,5,]),'fdisk_block':([0,2,],[6,6,]),'mkdisk_params':([7,],[11,]),'mkdisk_param':([7,11,],[12,18,]),'fdisk_params':([9,],[15,]),'fdisk_param':([9,15,],[16,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> commandsI','init',1,'p_init','grammar.py',76),
  ('commandsI -> commandsI command','commandsI',2,'p_commands','grammar.py',80),
  ('commandsI -> command','commandsI',1,'p_commands','grammar.py',81),
  ('command -> mkdisk_block','command',1,'p_command','grammar.py',89),
  ('command -> rmdisk_block','command',1,'p_command','grammar.py',90),
  ('command -> fdisk_block','command',1,'p_command','grammar.py',91),
  ('mkdisk_block -> MKDISK mkdisk_params','mkdisk_block',2,'p_mkdisk_block','grammar.py',95),
  ('rmdisk_block -> RMDISK SEPARATOR PATH ASSIGN PATHWITHQUOTES','rmdisk_block',5,'p_rmdisk_block','grammar.py',100),
  ('rmdisk_block -> RMDISK SEPARATOR PATH ASSIGN PATHWITHOUTQUOTES','rmdisk_block',5,'p_rmdisk_block','grammar.py',101),
  ('mkdisk_params -> mkdisk_params mkdisk_param','mkdisk_params',2,'p_mkdisk_params','grammar.py',105),
  ('mkdisk_params -> mkdisk_param','mkdisk_params',1,'p_mkdisk_params','grammar.py',106),
  ('mkdisk_param -> SEPARATOR SIZE ASSIGN NUMBER','mkdisk_param',4,'p_mkdisk_param','grammar.py',114),
  ('mkdisk_param -> SEPARATOR PATH ASSIGN PATHWITHQUOTES','mkdisk_param',4,'p_mkdisk_param','grammar.py',115),
  ('mkdisk_param -> SEPARATOR PATH ASSIGN PATHWITHOUTQUOTES','mkdisk_param',4,'p_mkdisk_param','grammar.py',116),
  ('mkdisk_param -> SEPARATOR UNIT ASSIGN ID','mkdisk_param',4,'p_mkdisk_param','grammar.py',117),
  ('mkdisk_param -> SEPARATOR FIT ASSIGN ID','mkdisk_param',4,'p_mkdisk_param','grammar.py',118),
  ('fdisk_block -> FDISK fdisk_params','fdisk_block',2,'p_fdisk_block','grammar.py',132),
  ('fdisk_params -> fdisk_params fdisk_param','fdisk_params',2,'p_fdisk_params','grammar.py',136),
  ('fdisk_params -> fdisk_param','fdisk_params',1,'p_fdisk_params','grammar.py',137),
  ('fdisk_param -> SEPARATOR SIZE ASSIGN NUMBER','fdisk_param',4,'p_fdisk_param','grammar.py',145),
  ('fdisk_param -> SEPARATOR PATH ASSIGN PATHWITHQUOTES','fdisk_param',4,'p_fdisk_param','grammar.py',146),
  ('fdisk_param -> SEPARATOR PATH ASSIGN PATHWITHOUTQUOTES','fdisk_param',4,'p_fdisk_param','grammar.py',147),
  ('fdisk_param -> SEPARATOR NAME ASSIGN ID','fdisk_param',4,'p_fdisk_param','grammar.py',148),
  ('fdisk_param -> SEPARATOR NAME ASSIGN PATHWITHOUTQUOTES','fdisk_param',4,'p_fdisk_param','grammar.py',149),
  ('fdisk_param -> SEPARATOR UNIT ASSIGN ID','fdisk_param',4,'p_fdisk_param','grammar.py',150),
  ('fdisk_param -> SEPARATOR TYPE ASSIGN ID','fdisk_param',4,'p_fdisk_param','grammar.py',151),
  ('fdisk_param -> SEPARATOR FIT ASSIGN ID','fdisk_param',4,'p_fdisk_param','grammar.py',152),
  ('fdisk_param -> SEPARATOR DELETE ASSIGN ID','fdisk_param',4,'p_fdisk_param','grammar.py',153),
  ('fdisk_param -> SEPARATOR ADD ASSIGN ID','fdisk_param',4,'p_fdisk_param','grammar.py',154),
]
